project:
  type: website
  output-dir: docs

website:
  title: "Riccardo Corradin"
  search: false
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: dissertations.qmd
        text: Dissertations
      - href: misc.qmd
        text: Miscellanea

format:
  html:
    theme: simplex
    css: styles.css
    toc: false
    page-layout: full
    fontsize: 1.1em

editor: visual

