project:
  type: website
  output-dir: docs
  resources:
    - /files
    - /img
    - /data

website:
  title: Riccardo Corradin
  search: false
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: dissertations.qmd
        text: Supervision

format:
  html:
    embed-resources: true
    smooth-scroll: true
    theme: [simplex]
    # theme: [simplex, theme.scss]
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 3
    linkcolor: darkblue
    page-layout: full
    fontsize: 1.1em
    css: styles.css

editor: visual

